name: writing samples
favicon: null
layout_spectrum: 0.8674804135225713
typography_spectrum: 0.6649375592824072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.548890323145315
  lightness: 0.037031350657343864
  saturation: 0.5797216130886227
  rhythmicContrast: 0.08612524927593768
purpose: []
